### ISSUE TITLE
Question about 'max: [xxx]'

### ISSUE THREAD

**Issue by Rubiczhang** [riscv-software-src/riscv-config#82]
Hello everyone, I'm a Newbie who study yaml and cerberus first time. I found that in riscv_config/schemas:line 181. The key 'max' has a value '[56]'.

```yaml
    physical_addr_sz:
      type: integer
      max: [56]
      required: true
      check_with: phy_addr
```

As far as I can see, '[56]' seems to be a list with one element. But the type of physical_addr_sz is integer. It seems impossible to compare an integer with a list. 

I don't konw whether it's a bug or it's just a feature I haven't known.
